version: '3.8'

services:
  mysql-hanzi:
    image: mysql:8.0
    container_name: mysql-hanzi
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "hanzi_db"
    ports:
      - "3306:3306"
    volumes:
      - mysql_hanzi_data:/var/lib/mysql
      - ./database/hanzi_scripts:/docker-entrypoint-initdb.d
      - ./database/data_prep/dataset/clean:/var/lib/mysql-files
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mysql_hanzi_data:
    driver: local

networks:
  backend:
    driver: bridge
